STATE_DICT = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming",
    # "PR": "Puerto Rico" # DON'T INCLUDE
}
MEMBERS = {
    "Tammy Baldwin": "B001230",
    "John Barrasso": "B001261",
    "Michael F. Bennet": "B001267",
    "Richard Blumenthal": "B001277",
    "Roy Blunt": "B001236",
    "Cory Booker": "B001288",
    "Sherrod Brown": "B001135",
    "Marsha Blackburn": "B001291",
    "Barbara Boxer": "B000711",
    "John Boozman": "B001267",
    "Sherrod Brown": "B001135",
    "Richard Burr": "B001135",
    "Maria Cantwell": "C000127"
    # Need to add all the names or a easier way to store member ID's or remove this and create a function to pull from the already API.
}